### ISSUE TITLE
[sturgeon] Settings interface problem after opkg update

### ISSUE THREAD

**Issue by tomi7711** [AsteroidOS/asteroid#225] opened 2022-10-11 19:54 UTC
I updated AsteroidOS with opkg update/upgrade command from ssh. After that I wanted to restart from the Setting but istead of the Setting menu, there is a completely white screen. I can't do anything. I restarted the OS with the button but the problem still exists, I don't see the menu items, just a white screen. Can I do something about it or reflash it?
The screen gestures are working, the system does not freeze so I can go back to the main screen.
Thanks!

**Comment by beroset** [comment] 2022-10-29 20:34
I believe this was due to a mismatch of packages.  Some used the more recent controls within `qml-asteroid` but the `qml-asteroid` package itself was not updated.  To test this try updating just the `qml-asteroid` package and then restart the watch (or just do `systemctl restart user@1000` as root on the watch to do a minimal restart.

**Comment by MrRocketFX** [comment] 2022-11-03 13:06
I was unaware of the existence of a package manager gonna try updating it right now

**Comment by beroset** [comment] 2022-11-05 21:13
Although this was entered first, I think this should be marked Closed and as a duplicate of #226

**Closed** 2023-03-01 00:40 UTC
