### ISSUE TITLE
[bass] Battery icon in background

### ISSUE THREAD

**Issue by bskyh** [AsteroidOS/asteroid#108] opened 2019-12-31 07:39 UTC
![IMG_0517](https://user-images.githubusercontent.com/22071770/71613827-6d53cb00-2be3-11ea-9eb2-c64371831cc5.JPG)
![IMG_0516](https://user-images.githubusercontent.com/22071770/71613828-6f1d8e80-2be3-11ea-90a1-529c9163b9ef.JPG)
![IMG_0518](https://user-images.githubusercontent.com/22071770/71613829-70e75200-2be3-11ea-99b0-055ea2625a7a.JPG)

bass DSME[378]: batterytracker: FAILED to read /run/state/namespaces/Battery/ChargePercentage
bass DSME[378]: batterytracker: FAILED to read /run/state/namespaces/Battery/IsCharging
bass DSME[378]: batterytracker: No battery data available

**Comment by bskyh** [comment] 2019-12-31 07:44
can you help me to fix that, thanks a lot

**Comment by FlorentRevest** [comment] 2020-01-06 20:38
The DSME logs errors are unrelated.
I suspect something is wrong with the graphic stack instead. But I have no clue what's happening. As far as I know this hasn't happened to anyone else.

**Comment by FlorentRevest** [comment] 2022-01-21 09:41
We believe this is screen burn-in https://en.m.wikipedia.org/wiki/Screen_burn-in
First of all because it is relatively common on smartwatch screens when a static white on black image is shown for a long time. Also because the battery icon that is « printed » everywhere is the LG charging logo so it does not show up anywhere in AsteroidOS itself. Also because this is the only report of this bug we ever got so we are pretty confident this is hardware specific. This should be confirmed if flashing a different ROM also has the same issue.
Unfortunately I don’t think there is anything you can do about this. There’s even less we can do about it so I’ll close this bug

**Closed by FlorentRevest** 2022-01-21 09:41 UTC
