### ISSUE TITLE
Cannot asteroid on sony smartwatch 3

### ISSUE THREAD

**Issue by themester** [AsteroidOS/asteroid#38] opened 2017-09-12 19:14 UTC
mester > sudo fastboot flash userdata asteroid-image-tetra.ext4 
target reported max download size of 425721856 bytes
Invalid sparse file format at header magi
erasing 'userdata'...
OKAY [  9.256s]
sending sparse 'userdata' 1/2 (410009 KB)...
OKAY [ 18.367s]
writing 'userdata' 1/2...
FAILED (remote: unknown chunk type in sparse image)
finished. total time: 27.655s

**Comment by comradekingu** [comment] 2017-09-12 20:01
Did you checksum the downloaded image?

**Comment by FlorentRevest** [comment] 2017-09-12 20:03
This is a duplicate of https://github.com/AsteroidOS/asteroid/issues/31 and a known bug. I close this issue, please follow the other thread.

**Closed by FlorentRevest** 2017-09-12 20:03 UTC

**Comment by themester** [comment] 2017-09-13 07:24
@FlorentRevest I readed the other issue, and don't explain the solution
