### ISSUE TITLE
[bass] Battery indicator showing "undefined%"

### ISSUE THREAD

**Issue by CharlesCage** [AsteroidOS/asteroid#95] opened 2019-09-18 21:52 UTC
v1.0 / bass

New install, first flash. Battery indicator shows empty with "undefined%"

Charge before reflash was 70%

Tried restart as well.

**Comment by JNissi** [comment] 2019-09-25 09:26
Duplicate of #94 with different hardware, so the problem is probably in meta-asteroid. (?)

**Comment by FlorentRevest** [comment] 2019-09-27 22:32
The problem is most likely in meta-asteroid indeed.
@CharlesCage I'd redirect you to my answer in #94 for now https://github.com/AsteroidOS/asteroid/issues/94#issuecomment-536114052

**Comment by MagneFire** [comment] 2022-01-23 12:41
Since https://github.com/AsteroidOS/meta-asteroid/pull/83 has been merged. So this issue is finally solved :tada:

**Closed by MagneFire** 2022-01-23 12:41 UTC
